### ISSUE TITLE
flag type in definition 

### ISSUE THREAD

**Issue by yousef-soliman** [open-feature/spec#108]
i think it will be better to define the flag type in a definition like this

``` json
"myBoolFlag": {
      "state": "ENABLED",
      "type": "BOOLEAN",
      "variants": {
        "on": true,
        "off": false
      },
      "defaultVariant": "on"
    },
```
it will let us abstract the endpoints at [flagd](https://github.com/open-feature/flagd)
``` go
"/flags/{flag-key}/resolve/boolean"
"/flags/{flag-key}/resolve/numbe"
"/flags/{flag-key}/resolve/object"
"/flags/{flag-key}/resolve/string"
```
to one endpoint 
```go
"/flags/{flag-key}/resolve/"
```

**Comment by toddbaert** [comment]
As a somewhat related point... we do have some code duplication in flagd as a consequence of this, and the generated endpoints. I would like to eventually rectify that issue with an upgrade to go 1.18 and the use of generics.

**Comment by toddbaert** [comment]
Closing this for now
