### ISSUE TITLE
Oversight: We don't have a mechanism to order hooks

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/spec#114]
There's not currently a way, according to the spec, to control the ordering of specs WITHIN the "before" stage. Given these short-circuit (e.g. if an error happens, we skip the rest of the hooks), this seems like an oversight.

**Comment by toddbaert** [comment]
>There's not currently a way, according to the spec, to control the ordering of specs WITHIN the "before" stage.

Do you mean the "ordering of _hooks_"?

Yes, I think this might be a miss... I think most implementations run them in the order applied, with the other stages running in reverse order... but we seemed to have neglected to mention this.

**Comment by toddbaert** [comment]
@justinabrahms - any more thoughts on this? Should we add a point to the spec saying that within a stage they run in the order added? All SDKs work this way, so it won't be a big deal.

If you think we need something more than that, I'm interested in proposals!

**Comment by justinabrahms** [comment]
Fine to drop this for now.
