### ISSUE TITLE
backend only?

### ISSUE THREAD

**Issue by trondhindenes** [open-feature/spec#13]
Hi, this is a really interesting initative! I just briefly read thru the specs, and it seems to me that this is primarily targeted at backend apps, since it relies on sidecar apps and crds etc.
How about frontends that might run direcly off of a cdn coupled with s3 or similar static storage? Or mobile apps?

It would be good if the spec at least mentioned how "non-backend" apps would integrate with this

**Comment by beeme1mr** [comment]
The priority of client-side feature flagging will be discussed in #65
