### ISSUE TITLE
Evaluation Context Merging 3.2.2 is missing before hooks

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/spec#131]
[Requirement 3.2.2](https://github.com/open-feature/spec/blob/main/specification/sections/03-evaluation-context.md#requirement-322) should included the before hook.

`API (global) -> client -> invocation -> before hooks`

An explanation of why the before hook has the highest priority should be included in the non-normative section.

**Comment by toddbaert** [comment]
I mentioned this in a previous PR and I'm not sure about it...

I'm not sure I agree. This doesn't really have much to do with hooks - it's really about setting context at various levels. Personally, I would rather get rid of this requirement entirely then basically have the exact same information in 2 places.

**Comment by toddbaert** [comment]
Maybe we could just have a link in the non-normative section of 3.2.1 to 4.3.4?
