### ISSUE TITLE
Evaluation Context related error status

### ISSUE THREAD

**Issue by kinyoklion** [open-feature/spec#141]
For some providers contexts are going to require certain attributes to function correctly. For instance a targeting key.

It would be good if there was an error code for context related problems, for instance `MALFORMED_CONTEXT`.

This would help to more quickly narrow down usage errors.

**Comment by toddbaert** [comment]
I agree this would be helpful. I'd accept `MALFORMED_CONTEXT`, but I'll also suggest `INVALID_CONTEXT` as another possible alternative. "Malformed" suggests to me something like a structural error, while "invalid" implies either structural or semantic issues (like a missing targeting key). I think either work though.

**Comment by thomaspoignant** [comment]
Yes it would be great to have something like that in the providers to be explicit when a field is missing.

**Comment by kinyoklion** [comment]
Resolved in https://github.com/open-feature/spec/pull/142
