### ISSUE TITLE
Where is spec for a flag?

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/spec#145]
The example_flags.json shows a flag to be:

```
"myStringFlag": {
  "state": "ENABLED",
  "variants": {
    "key1": "val11",
    "key2": "val2"
  },
  "defaultVariant": "key1"
}
```

Where are these fields listed in the spec?

**Comment by thomaspoignant** [comment]
This part is the implementation of feature flags in flagD not all providers are using the same format.

I don't think we should put flagD specifics in the open-feature spec.

**Comment by beeme1mr** [comment]
The JSON schema for those flag definitions can be found [here](https://github.com/open-feature/schemas/blob/main/json/flagd-definitions.yaml). However, as Thomas mentioned, it's specific to flagd and was not intended to be included in the spec.  I created [this issue](https://github.com/open-feature/flagd/issues/179) to add some more information to the FlagD docs.
