### ISSUE TITLE
[bug] Multiple providers bound to one "name", and associated issues

### ISSUE THREAD

**Issue by benjiro** [open-feature/spec#192]
Spec: open-feature/spec@a4ffec3
See: https://github.com/open-feature/dotnet-sdk/issues/126

The spec allows a single instance of a provider to be bound to multiple names (even if it didn't allow this, any naive implementation would probably allow it to happen). We either need to prevent it or specify how it should work. We may want to specify that providers that are still bound to any client name are not shut down.  - @toddbaert 

I consider this a spec bug personally, because it constitutes a problematic ambiguity in the spec. - @toddbaert 

cc @justinabrahms 

Quote from @kinyoklion :+1: 

> Basic case.
> ```
> var provider1 = new TestProvider();
> 
> openFeature.SetProvider("a",  provider1);
> 
> // Call init on provider1?
> 
> openFeature.SetProvider("a",  new TestProvider());
> 
> // Call shutdown on provider 1?
> 
> // Call init on new provider.
> 
> ```
> 
> Two Names Scenario 1.
> ```
> var provider = new TestProvider();
> 
> openFeature.SetProvider("a", provider);
> 
> // Call init on provider?
> 
> openFeature.SetProvider("b", provider);
> 
> // Provider already has init called. Do we call it again?
> 
> ```
> 
> Two Names Scenario 2.
> ```
> var provider1 = new TestProvider();
> 
> openFeature.SetProvider("a", provider1);
> openFeature.SetProvider("b", provider1);
> 
> openFeature.SetProvider("b",  new TestProvider());
> 
> // We don't want to shutdown provider1, because it is still registered to "b".
> 
> ```

**Comment by toddbaert** [comment]
cc @lopitz @lukas-reining

**Comment by toddbaert** [comment]
@benjiro FYI I moved this from the dotnet-sdk repo.

**Comment by lukas-reining** [comment]
I totally agree.
Also found that and implemented it in the JS SDK the way that this does not happen for the case between named and unnamed providers.
But scenario 2 is not handled by the JS SDK now, I will fix that @toddbaert.

**Comment by toddbaert** [comment]
> I totally agree. Also found that and implemented it in the JS SDK the way that this does not happen for the case between named and unnamed providers. But scenario 2 is not handled by the JS SDK now, I will fix that @toddbaert.

Let's wait for now to build some consensus, just so that you dont implement something that you have to change. Do you agree with the solution I've vaguely proposed?

**Comment by lukas-reining** [comment]
Yes I totally agree with that @toddbaert, this is fixing at least the shutdown for me.
I already did that, was just 3 lines of code and a test.
Will add the PR and we can merge it or change it once we have concencus what do you think?

**Comment by toddbaert** [comment]
> Yes I totally agree with that @toddbaert, this is fixing at least the shutdown for me. I already did that, was just 3 lines of code and a test. Will add the PR and we can merge it or change it once we have concencus what do you think?

For now maybe add the PR here for reference.

**Comment by toddbaert** [comment]
Reading the spec a bit more, I think [1.1.2.2](https://openfeature.dev/specification/sections/flag-evaluation#requirement-1122) and [1.1.2.3](https://openfeature.dev/specification/sections/flag-evaluation#requirement-1123) _technically_ addresses these concerns, though the non-normative helper-text could be improved.

**Comment by justinabrahms** [comment]
Thanks Todd.
I agree with what's been stated:

basic:
- yes call init there
- yes, call shutdownthere

2 names:
- call init when set
- if already init'd, don't do it again

2 names 2:
- don't shut down p1

**Comment by toddbaert** [comment]
I think this is taken care of with https://github.com/open-feature/spec/pull/193. Please re-open if you disagree, @benjiro
