### ISSUE TITLE
Implement support for a retry strategy during flag evaluation

### ISSUE THREAD

**Issue by NicklasWallgren** [open-feature/spec#286]
I believe it would be beneficial for providers to support a retry strategy when evaluating a flag, to account for scenarios such as I/O issues or similar errors.

**Comment by nicklasl** [comment]
I’d like to hear the community’s input and whether this has been addressed before. Personally, I’m not convinced this is something the spec should dictate.

It might be better for each provider/vendor to handle this independently, keeping the functionality abstract and opaque to the Open Feature SDK.

**Comment by beeme1mr** [comment]
I agree it's likely a provider concern that doesn't need to be spec'd. Configuring a provider to retry with the current spec should be possible. However, I'm not aware of any provider that retries a failed evaluation. It's technically possible but could introduce a significant performance impact.

@NicklasWallgren, have you run into a limitation with the current spec that prevents retries?
