### ISSUE TITLE
Hook ordering & state

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/spec#40]
We need to have a concept of hook ordering. In our case, we have a client hook `EmitMetrics`. Sometimes, devs don't want to emit metrics, so we want to selectively overwrite it.

```python
client.registerHook(EmitMetrics())

client.getBooleanValues('key', defaultValue) # This emits metrics

client.getBooleanValues('key', defaultValue, FlagOptions(DONT_EMIT_METRICS)) # This doesnt emit metrics.
```

We're thinking that we'll build this like:

```python
class EmitMetrics:
  def after(ctx, details):
    if not ctx.state['dont-emit-metrics']:
      emitMetrics()

class DONT_EMIT_METRICS:
  def before(ctx):
    ctx.state['dont-emit-metrics'] = True
```

This means we'll need precise control around when hooks run (with associated APIs to insert at specific ordering) as well as a change to HookContext to hold some state.

**Comment by toddbaert** [comment]
I think well-defined ordering is certainly a good idea, and a necessity. I created a stub markdown file for hooks in the spec: `specification/flag-evaluation/hooks.md`. We should mention that topic when we flesh it out.

I'm less sure about storing arbitrary state on the HookContext. It might be the right approach, but I also am wary of encouraging dependencies between hooks like this. It could be a footgun.

In the sample [OTel Hook](https://github.com/open-feature/sdk-research/blob/main/packages/openfeature-extra/src/lib/hooks/open-telemetry-hook.ts), we used a private WeakMap member (Java has this concept too: https://docs.oracle.com/javase/7/docs/api/java/util/WeakHashMap.html) to store state, using the Hook Context object reference itself as the key. This means that only the OTel hook can access this map, and so only it can modify state stored in this map having to do with it's OTel related logic, maintaining good separation of concerns. Another nice aspect of this pattern is that when the HookContext is garbage collected the values it indexes in the WeakMap  are as well.

**Comment by justinabrahms** [comment]
Without passing state, I'm not clear how we could represent:

I want this hook to do the thing it does on every invocation... except this one in particular.

The other thing we've talked about is having users put some sentinel values within the evaluation context, which feels super gross. 

Maybe we have some immutable state that's included on FlagEvaluationOptions when the user kicks off the request?

**Comment by beeme1mr** [comment]
Addressed by hook hints
