### ISSUE TITLE
Evaluation Context Specification

### ISSUE THREAD

**Issue by toddbaert** [open-feature/spec#43]
We need to draft a specification for the Evaluation Context. It must define things such as:

- standard fields on the context (these must be defined so they can be predictably mapped to standard fields in some SDKs, such as ip-address, email, http-method, etc)
- where context attributes can be provider (at API level (for static data such as runtime or application name), per client, as a parameter for flag evaluation)
- how context provided at different levels mentioned above will be merged
- implicit propagation mechanisms (continuations, thread local storage, etc)

And possibly more. 

Related discussions: 

- [user identifier](https://github.com/open-feature/sdk-research/issues/3)
- [system, request properties, context propagation](https://github.com/open-feature/sdk-research/issues/6)

**Comment by weyert** [comment]
I would suggest distinctId as in distinct identifier, for e.g. user, group, company etc
