### ISSUE TITLE
Don't allow exceptions during client creation

### ISSUE THREAD

**Issue by moredip** [open-feature/spec#44]
I just noticed that the current draft spec has:

> Requirement 1.19
> No methods, functions, or operations on the client should ever throw exceptions, or otherwise abnormally terminate. Flag evaluation calls must always return the default value in the event of abnormal execution. Exceptions include functions or methods for the purposes for configuration or setup.

I understand the motivation for never throwing exceptions, but I think we're failing to meet the spirit of this for client-side JS if we allow exceptions when creating a client, because of the unique lifecycle of browser-based apps. For a client-side app the client is often created just before an evaluation is done, so an exception thrown during client creation is pretty much just as disruptive as an exception when you call a method.

Because of this, I would propose that the spec not allow exceptions during client creation.

**Comment by toddbaert** [comment]
This also might relate to a question that's come up a few times: do we want to expose events (specifically readiness events) from the provider interface? Providers could sidestep this by requiring SDKs that have a readiness event simply be ready BEFORE passing them into the provider. For instance, the CloudbeesProvider may require an already-initialized Cloudbees SDK instance. Not sure.

**Comment by toddbaert** [comment]
I guess the only question here is if we should specifically add a requirement that `.getClient()` calls never throw. I think it's probably a good thing to do.
