### ISSUE TITLE
Define a Feature Flag in the Glossary

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/spec#47]
The term feature flag is used throughout the project. A formal definition of what that means should be added to the glossary.

**Comment by moredip** [comment]
My general one-sentence description is usually something like: "A mechanism which allows an engineer to define alternative codepaths within a deployed piece of software, and then choose between those codepaths at runtime based on some sort of decision criteria"

**Comment by beeme1mr** [comment]
Thanks @moredip! I added a slight variation of your suggestion.
