### ISSUE TITLE
Should `after` hooks be allowed to mutate the value?

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/spec#48]
Pro: you can do a json -> instance mapping in there, which would be rad.
Con: subsequent hooks don't get the json value anymore, which may be very surprising to them.

**Comment by moredip** [comment]
I think another con would be it would make type signatures really fiddly, and/or we'd lose a lot of type safety.

**Comment by beeme1mr** [comment]
We could allow the after hook to mutate the value but require that the type signature itself doesn't change.
