### ISSUE TITLE
Merge json specs into a single file and put it at a known URL

### ISSUE THREAD

**Issue by justinabrahms** [open-feature/spec#62]
This will be useful for validating, for instance, that we've got test cases that cover all of the spec files.

**Comment by beeme1mr** [comment]
I think this would be a great change. It may also be a good opportunity to have a different number per section. That could determine the order of the list. For example, the output could be something like this:

```
[{
  name: "Flag Evaluation API",
  requirements: [....]
}, {
  name: "Provider",
  requirements: [....]
}, ...
]
```

The generated output could be saved in the repo and the raw file be used as the known URL.
