### ISSUE TITLE
Document the required structure of specifications

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/spec#7]
**What are you trying to achieve?**

OpenFeature specifications need to be well structured and easy to understand. W3C has a [QA framework for specification guidelines](https://www.w3.org/TR/qaframe-spec/) that may be useful for standardizing the spec. OpenTelemetery also had a [PR](https://github.com/open-telemetry/opentelemetry-specification/pull/2003) that automatically extracted properly formatted specs into JSON.

No matter what approach is chosen, it should be documented so the spec remains consistent.

**Comment by toddbaert** [comment]
Closed. This is captured in current doc/spec, and we have an issue for some automation: https://github.com/open-feature/spec/issues/36.
