### ISSUE TITLE
Add requirements/clarification specifying context can be provided globally, at client creation, and flag evaluation

### ISSUE THREAD

**Issue by toddbaert** [open-feature/spec#75]
Similarly to hooks, I think we want to allow setting global, client, and evaluation context. We will also need to describe how they are merged. This should be a fairly minor change to the spec, unless we want to get fancy with how to merge the contexts. We can mention it in the Evaluation Context spec, and link to the new requirements in the Flag Evaluation spec.

I'm proposing a simple merge where the invocation context overwrites properties in the client context, which overwrites properties in the global context:

```
    // merge global, client, and evaluation context
    const mergedContext = {
      ...globalContext,
      ...clientContext,
      ...invocationContext,
    };
```

Another option would be to define a merge function so that app-authors could have full control of how the merge works, perhaps with the above as a default.

**Comment by justinabrahms** [comment]
I dislike a custom merge function but we can add one later if we need to. This works for me.

Before Hook generated context will sit between invocation and client context.

**Comment by beeme1mr** [comment]
Resolved by:

- https://github.com/open-feature/spec/blob/main/specification/flag-evaluation/flag-evaluation.md#requirement-13
- https://github.com/open-feature/spec/blob/main/specification/flag-evaluation/flag-evaluation.md#requirement-16
- https://github.com/open-feature/spec/blob/main/specification/flag-evaluation/flag-evaluation.md#requirement-117
