### ISSUE TITLE
Events Specification

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/spec#77]
### Summary

Many vendors support an event-based API that allows developers to subscribe for events. This can be used to detect when the SDK is ready to perform flag evaluation or a flag configuration changes.

### Events

The following events should be considered defining the spec.

| Name  | Description|
| ------------- | ------------- |
| PROVIDER_STATUS  | Provider status would emit events around the lifecycle of a provider. This could include events like "ready". This could be used to ensure that the provider has started and is ready to perform flag evaluation.  |
| FLAG_CONFIG_UPDATE | Flag config update would emit events when a flag configuration changes. This could be used to detect that a flag configuration has changed and instantiate a new object.  |

### References

- [LaunchDarkly](https://docs.launchdarkly.com/sdk/features/flag-changes)
- [Harness](https://ngdocs.harness.io/article/3v7fclfg59-node-js-sdk-reference#step_5_add_methods_to_register_the_events)
- [Split](https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK#manager)

**Comment by InTheCloudDan** [comment]
for LaunchDarkly we have it a bit deeper than just `FLAG_CONFIG_UPDATE`. You can pass in a context that when the update(rule changes) affects the return valuation for that specific context then the event is emitted.

**Comment by agentgonzo** [comment]
CloudBees also has a [ConfigurationFetchedHandler](https://docs.cloudbees.com/docs/cloudbees-feature-management/latest/reporting/configuration-fetched-handler) that can notify the client when flag configurations are changed in the dashboard.

**Comment by agentgonzo** [comment]
https://github.com/open-feature/java-sdk/pull/30 for an idea on implementing it.

**Comment by toddbaert** [comment]
I'm going to close this since we have an OFEP that's a better platform for concrete discussion.
