### ISSUE TITLE
Event Tracking API Specification

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/spec#78]
### Summary

More advanced feature flagging use cases often require capturing events that can be related to a particular flag evaluation. That allows teams to more easily track that a new feature had the intended impact.

This concept does not exist in all vendors/providers. However, we could potentially introduce the concept of a tracking provider. The provider could either be a feature flag vendor that supports this concept or another event tracking tool (e.g. Segment).

**A general event tracking API is out of scope.**

### References
 - [Split](https://help.split.io/hc/en-us/articles/360058730852-Browser-SDK#multiple-evaluations-at-once)
 - [LaunchDarkly](https://launchdarkly.github.io/node-server-sdk/interfaces/_launchdarkly_node_server_sdk_.LDClient.html#track)
 - [Flagsmith](https://docs.flagsmith.com/advanced-use/ab-testing)

**Comment by weyert** [comment]
This is something that would be useful for PostHog were you occasionally want to identify groups by sending a `$groupIdentify`-event useful when you want to enable a feature flag for a specific company or tenant but before you can use such a filter for the feature flag you first need to identify some entries for the group hence this event.

**Comment by beeme1mr** [comment]
Closing in favor of [the research issue](https://github.com/open-feature/research/issues/16).
