### ISSUE TITLE
Flag Tracker Specification

### ISSUE THREAD

**Issue by InTheCloudDan** [open-feature/spec#83]
Do we want to define the ability to set a callback function when a feature flag is updated? LaunchDarkly has the concept of `FlagTracker`, that you can pass in an optional context for, that calls the function whenever a change affecting that flag is sent: https://launchdarkly.github.io/java-server-sdk/com/launchdarkly/sdk/server/interfaces/FlagTracker.html

**Comment by beeme1mr** [comment]
Hey @InTheCloudDan, I opened #77 yesterday. Is that what you had in mind?

**Comment by InTheCloudDan** [comment]
@beeme1mr yes, I missed that below the `Event Tracking` spec!
