### ISSUE TITLE
Previously created clients should always use currently registered provider

### ISSUE THREAD

**Issue by toddbaert** [open-feature/spec#96]
I was making a [change](https://github.com/open-feature/node-sdk/pull/20) to the Node SDK to remove the provider accessor from the API (https://github.com/open-feature/spec/issues/84, https://github.com/open-feature/spec/pull/93) and in moving things around, I briefly changed behavior in a pretty nefarious way. Basically, I created a situation wherein clients maintained the provider that was registered at the time of their creation:

```
OpenFeature.setProvider(providerX)
clientA = OpenFeatire.getClient();
Openfeature.setProvider(providerY)
clientB = OpenFeatire.getClient();

clientA.getBooleanValue() // this was still using providerX
clientB.getBooleanValue() // this was using providerY
```
I think this is _not good_ :tm:  . It means authors would have to "keep track" of the creation time of certain clients, and causes a lot of other surprising knock-on effects. I don't think it technically violates our singleton requirement (the API object is still a singleton) but it feels like it violates it practically...

Should we mention the expectation that all clients use the currently registered provider in the spec? Is such a requirement already implied? Can we just add some verbiage to the singleton requirement?

@justinabrahms @davejohnston @beeme1mr

**Comment by justinabrahms** [comment]
I was actually thinking of a world where we had multiple clients, one for each provider. This would allow me to have a config-backed provider and a service-backed one.  I might also have a single aggregate provider, but would need to do something w/ FlagEvalOptions to make it work.

Would love to better understand the use-case you're seeing w/ updating the provider to be different and have it reflect in existing clients.

**Comment by toddbaert** [comment]
I think this discussion might merit a meeting, either during our standing one, or something dedicated.

**Comment by justinabrahms** [comment]
I think I like that. My preference is we leave this ticket open until post-alpha bc this doesn't seem necessary to hit that goal and I want a stable spec to shoot for. :)

Or maybe we tag an alpha spec that I can work towards.

**Comment by toddbaert** [comment]
I'm going to close this now, and we can revive it if it comes up again... I think it's a bit of an edge case.
